name: check-pr

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  changed-files: # https://dev.to/scienta/get-changed-files-in-github-actions-1p36
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all }}
      js: ${{ steps.changes.outputs.js }}
    steps:
      # Make sure we have some code to diff.
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Debug
        run: |
          echo "::debug::$(pwd)"
          echo "::debug::$(ls)"
          echo "::debug::$(git status)"
          echo "::debug::$(git log --online)"
          echo "::debug::$(git show ${{ github.sha }})"
          echo "::debug::$(git show ${{ github.event.pull_request.base.sha }})"
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=js::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep --extended-regexp '\.js(on)?$' | xargs)"

  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changed-files
    # only run there are changed files
    if: ${{ needs.changed-files.outputs.js }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: echo changed files
        run: echo ${{ needs.changed-files.outputs.js }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
      - name: Install /package.json dependencies
        run: npm install
      - name: Run /package.json linter (eslint)
        run: npm run eslint ${{ needs.changed-files.outputs.js }}

      # Runs a single command using the runners shell
      # - name: Run a one-line script
        # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        # run: |
          # echo Add other actions to build,
          # echo test, and deploy your project.
